### ISSUE TITLE
exercise 3 and onwards broken

### ISSUE THREAD

**Issue by JonathanSchwob** [ReactiveX/learnrx#173]
Greetings,

When clicking show answer then run I get a pop up showing: TypeError: videoAndTitlePairs.sortBy is not a function. 

The next exercise does not appear and there is no way that I know of to get it to show up. 

I think this is an amazing tool for learning FP, thanks for taking the time to create it.

**Comment by myshov** [comment]
@JonathanSchwob hi
There is pull request for fixing this issue here https://github.com/ReactiveX/learnrx/pull/170

I hope that @morenoh149 will merge that quickfix, because tutorial practically broken right now :(

P.S. By the way you can fork repo and replace broken url by yourself if you want working version of tutorial.

**Comment by morenoh149** [comment]
merged. Hope folks chime in if there are incompatibilities between rxjs v5 and v6.

**Comment by seanpoulter** [comment]
You should be able to close this issue @morenoh149. The exercises are OK up to 37.
